<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7415" started-at="2019-09-12T08:57:06Z" finished-at="2019-09-12T08:57:13Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7415" started-at="2019-09-12T08:57:06Z" finished-at="2019-09-12T08:57:13Z">
      <class name="mehmet.project.HomePageTest">
        <test-method status="PASS" signature="initializing()[pri:0, instance:mehmet.project.HomePageTest@1e7c7811]" name="initializing" is-config="true" duration-ms="3114" started-at="2019-09-12T08:57:06Z" finished-at="2019-09-12T08:57:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializing -->
        <test-method status="PASS" signature="invalidUserandPass()[pri:0, instance:mehmet.project.HomePageTest@1e7c7811]" name="invalidUserandPass" duration-ms="1220" started-at="2019-09-12T08:57:09Z" finished-at="2019-09-12T08:57:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidUserandPass -->
        <test-method status="PASS" signature="invalidUserandvalidPass()[pri:0, instance:mehmet.project.HomePageTest@1e7c7811]" name="invalidUserandvalidPass" duration-ms="769" started-at="2019-09-12T08:57:10Z" finished-at="2019-09-12T08:57:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidUserandvalidPass -->
        <test-method status="PASS" signature="validUserandInvalidPass()[pri:0, instance:mehmet.project.HomePageTest@1e7c7811]" name="validUserandInvalidPass" duration-ms="598" started-at="2019-09-12T08:57:11Z" finished-at="2019-09-12T08:57:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUserandInvalidPass -->
        <test-method status="FAIL" signature="validUserandPass()[pri:0, instance:mehmet.project.HomePageTest@1e7c7811]" name="validUserandPass" duration-ms="927" started-at="2019-09-12T08:57:12Z" finished-at="2019-09-12T08:57:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [**Successful Login**] but found [**Failed Login**]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [**Successful Login**] but found [**Failed Login**]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at mehmet.project.HomePageTest.validUserandPass(HomePageTest.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUserandPass -->
        <test-method status="PASS" signature="finishing()[pri:0, instance:mehmet.project.HomePageTest@1e7c7811]" name="finishing" is-config="true" duration-ms="748" started-at="2019-09-12T08:57:13Z" finished-at="2019-09-12T08:57:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finishing -->
      </class> <!-- mehmet.project.HomePageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
